version: '3.4'

services:
  rabbitmq:
    container_name: rabbit-container
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
