version: '3.4'

services:
  elasticsearch:
    container_name: es-container-vi
    image: thaichihien/elasticsearch-analysis-vietnamese:8.7.0
    restart: on-failure
    ports:
      - "9200:9200"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        hard: -1
        soft: -1
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "changeme"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
    networks:
      - elastic
  rabbitmq:
    container_name: rabbit-container
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
